name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge build
        run: |
          make build
        id: build

      - name: Run Forge tests
        run: |
          make test
        id: test

      - name: Run build benchmark
        run: |
          cd benchmarks/scripts
          npm install
          npm run generate
          cd ../../
          make build-benchmark
        id: build-benchmark

      - name: Run test benchmark
        run: |
          make test-benchmark
        id: test-benchmark
